name: my_first_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: 7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

assets:
  - asset: 'fonts/Poppins-Bold.ttf'
    weight: 800
  - asset: 'fonts/Poppins-Medium.ttf'
    weight: 500
  - asset: 'fonts/Poppins-Regular.ttf'
    weight: 400
  - asset: 'fonts/Poppins-SemiBold.ttf'
    weight: 600